defmodule MPG.Generator do
  @moduledoc """
  Generates content for the different game types
  """

  @things [
    "cannibals think about while dining",
    "dogs are actually saying when they bark",
    "grown-ups wish they could still do.",
    "you should never put in your mouth",
    "not to do in a hospital",
    "not to do while driving",
    "not to tell your mother",
    "paramedics shouldn't say to a patient on the way to the hospital",
    "people do when no one is looking",
    "that are good",
    "that are harder than they look",
    "that are your favorite foods",
    "that you can use to get from one place to another",
    "that confirm your house is haunted",
    "that confirm your life is going downhill",
    "that go bad",
    "that jiggle",
    "that make you feel stupid",
    "that make you giggle",
    "that make you uncomfortable",
    "that must be magic",
    "that shouldn't be made into video games",
    "that shouldn't be passed from one generation to the next",
    "that smell terrible",
    "that squirt",
    "that you will find in (name room of house..bathroom, kitchen, etc)",
    "that you can trip over",
    "that you love to watch on TV",
    "that you shouldn't do in public",
    "that you shouldn't swallow",
    "that you shouldn't throw off of a building",
    "that your parents would kill you for",
    "that would be fun to do in an elevator",
    "that would keep you out of heaven",
    "to wear to (occasion ...wedding, funeral, etc)",
    "wouldn't want to be allergic to",
    "you can never find",
    "you do to get a job",
    "you do to relieve stress",
    "you do to stay warm",
    "you don't want to find in your bed",
    "you might find in a library",
    "given to you for Christmas that you would return",
    "you shop for on Black Friday",
    "you should be thankful for",
    "you should do to get ready for winter",
    "you should give as birthday gifts",
    "you should never put in your mouth",
    "you shouldn't attempt to juggle",
    "you shouldn't do while babysitting",
    "you shouldn't do on your birthday",
    "you shouldn't do with glue",
    "you shouldn't give trick-or-treaters",
    "you shouldn't lick",
    "you shouldn't play catch with",
    "you shouldn't say when trying to make a good impression",
    "you shouldn't send your friends in a pic",
    "you shouldn't swallow",
    "you shouldn't tie to the roof of your car",
    "you use to remove snow from your car",
    "you wish for",
    "you would ask a psychic",
    "you would buy if you were rich",
    "you would do if you were a giant",
    "you would rather forget",
    "you would rather put off till tomorrow",
    "you would wish for if you were stranded on an island",
    "you wouldn't do for a million dollars",
    "you wouldn't want made into a movie",
    "you wouldn't want to do in cemetery",
    "you'd rather forget",
    "your friends text you",
    "your parents forgot to tell you",
    "you'll do when you retire",
    "that would get a doctor sued for malpractice",
    "you shouldn't do in front of a crowd",
    "that give you a headache",
    "you wouldn't want to clean",
    "a gentleman shouldn't do",
    "women know more about than men",
    "you shouldn't give as a gift",
    "that make you go ahhhh",
    "you shouldn't do at the dinner table",
    "you would consider strange to include on a resume",
    "there should be an award for",
    "you shouldn't do when having dinner with the Queen",
    "you shouldn't make fun of",
    "that make you giggle",
    "you shouldn't teach your pets to do",
    "you shouldn't photograph",
    "you shouldn't do in the classroom",
    "that make ballet more exciting",
    "men know more about then women",
    "you would say to a pig if it could talk",
    "you can do to get rid of unwanted guests",
    "you like about yourself",
    "you shouldn't say to your boyfriend/girlfriend",
    "you would line up to see",
    "a chicken thinks about when the farmer picks up the eggs",
    "you wish grew on trees",
    "you shouldn't say to you dentist",
    "you wish you could borrow from a library",
    "you shouldn't do while taking a final exam",
    "you shouldn't teach your parrot to say",
    "that go bad",
    "that shouldn't go into a time capsule",
    "that hurt your back",
    "you shouldn't mix",
    "you just can't believe",
    "that are politically incorrect",
    "that happen once in a blue moon",
    "about the opposite sex that frustrate you",
    "that are harder than they look",
    "kids know more about than adults",
    "that cause trouble",
    "that make you relax",
    "you wouldn't want to be allergic to",
    "you shouldn't shout at the top of your lungs",
    "you need to survive",
    "you shouldn't do in a car",
    "you would like to play with",
    "you can't stop",
    "you shouldn't do on vacation",
    "you would wish for if you found a genie in a bottle",
    "that seem to take an eternity",
    "that confirm you are losing your memory",
    "you shouldn't display in your china cabinet",
    "you would like as your last words",
    "that shouldn't be passed from one generation to the next",
    "you shouldn't put off until tomorrow",
    "that shouldn't be lumpy",
    "fish think about as they swim in their aquarium",
    "you could use as an excuse on judgement day",
    "that would make golf more exciting",
    "you shouldn't advertise in the classified ads",
    "you shouldn't do at home",
    "that would make work more exciting",
    "that are wild",
    "that require an assistant",
    "you would like to say to the President",
    "you would like to ask a psychic",
    "you shouldn't encourage your children to do",
    "you wish you could do with your feet",
    "you never see on television",
    "you wish worked by remote control",
    "you shouldn't exaggerate",
    "a waiter shouldn't do",
    "you shouldn't collect",
    "that confirm you still haven't grown up",
    "you shouldn't touch",
    "you shouldn't attempt at your age",
    "that confirm your small town is backward",
    "that would make school more exciting",
    "you shouldn't tie to the roof of your car",
    "you shouldn't send in the mail",
    "that usually make you feel better",
    "you would like to do on vacation",
    "that cause an accident",
    "you shouldn't say to get out of a speeding ticket",
    "you shouldn't say about your children",
    "you shouldn't hold while riding a bike",
    "you wish you could predict",
    "that hurt",
    "you shouldn't give away",
    "you hate as punishment",
    "you shouldn't advertise on a billboard",
    "that are embarrassing",
    "you shouldn't do in public",
    "that require a lot of patience",
    "you shouldn't say to your boss",
    "you shouldn't let an amateur do",
    "you wish you could erase",
    "you say to a telemarketer",
    "you wouldn't want to find in your sandwich",
    "you shouldn't put in your mouth",
    "that exhaust you",
    "you shouldn't do at the theatre",
    "you shouldn't do in the bathtub",
    "you shouldn't write on a Valentine's card",
    "you shouldn't say to your grandmother",
    "that make you jump",
    "you won't find in a dictionary",
    "you shouldn't say to a flight attendant",
    "you shouldn't put on the front lawn",
    "that drive you mad",
    "that jiggle",
    "you shouldn't do in your backyard",
    "you wouldn't want to find in your Christmas stocking",
    "you wish people would stop talking about",
    "you just can't beat",
    "you shouldn't do with your mouth open",
    "that would make your love life more exciting",
    "you shouldn't do at a party",
    "that are dirty",
    "you've paid too much for",
    "you shouldn't laugh at",
    "you should keep to yourself",
    "you wouldn't want your mother to talk about with your girlfriend/boyfriend",
    "you shouldn't do on your desk",
    "you would like to do in a blackout",
    "that make you cry",
    "you would do if you had super-human powers",
    "that are naughty",
    "that make you go ooooh",
    "that really need a referee",
    "you shouldn't put on the kitchen table",
    "you would do if you changed genders for a day",
    "you would rather forget",
    "that would be considered a bad habit",
    "you would rather be doing right now",
    "you shouldn't bite",
    "astronauts complain about in space",
    "you shouldn't do with your tongue",
    "you wouldn't want to know about your grandmother",
    "that make you gag",
    "you shouldn't say to your mother",
    "a chimp thinks about when he sees you at the zoo",
    "you shouldn't forget",
    "a doctor shouldn't do while performing surgery",
    "you shouldn't say to the First Lady",
    "you shouldn't do with glue",
    "you hate about the hospital",
    "that should have an expiration date",
    "you shouldn't do at the beach",
    "people like about you",
    "you shouldn't say to your doctor",
    "that confirm you are losing your mind",
    "that don't last very long",
    "you didn't realize until it was too late",
    "you keep hidden",
    "you would like to see in your horoscope",
    "you shouldn't lend",
    "that take courage",
    "you shouldn't say to your teacher",
    "you shouldn't do right after you eat",
    "you shouldn't do on your first day on the job",
    "you shouldn't do at the circus",
    "you shouldn't capture on videotape",
    "women talk about when they go to the restroom together",
    "that should come with a manual",
    "you shouldn't do on a first date",
    "that hang",
    "that confirm you have been abducted by aliens",
    "you never see in the country",
    "you shouldn't try to hold on to",
    "that prove you're in a bad restaurant",
    "you shouldn't say in group therapy",
    "that could get you arrested",
    "children shouldn't play with",
    "you shouldn't say to your father",
    "you want to do before you die",
    "you know nothing about",
    "a lady shouldn't do",
    "that confirm your car is a lemon",
    "that could result in a war",
    "you shouldn't say to your wife",
    "you would have a robot do",
    "cats think about humans",
    "you would do if you were a dictator",
    "you would like to change",
    "you would do if you were a giant",
    "you shouldn't pick up",
    "that would make meetings more exciting",
    "you never remember",
    "you keep in your car",
    "you shouldn't doodle on",
    "that don't make sense",
    "you wish you could do in your sleep",
    "you would like to study",
    "you might complain about in Hell",
    "you shouldn't celebrate",
    "you hope you can still do when you are 85",
    "you shouldn't share",
    "you will never see in your lifetime",
    "that could spoil your appetite",
    "you don't like about family gatherings",
    "that could use a good cleaning",
    "you shouldn't do on an airplane",
    "that are funny",
    "you hate to be called",
    "that would get you discharged from the army",
    "you would like to make someone do under hypnosis",
    "you shouldn't title a children's book",
    "that don't exist but you wish they did",
    "you shouldn't do with a computer",
    "you would like to do with a bald head",
    "that make you scream",
    "that would get you fired",
    "that warrant an apology",
    "you would hate to do for a living",
    "you shouldn't leave open",
    "that very old people shouldn't do",
    "you shouldn't do if you want to make a good first impression",
    "big dogs think about when they see a Chihuahua",
    "that make you feel young",
    "you shouldn't play catch with",
    "you shouldn't say to your troops before they go to battle",
    "you wish you didn't know",
    "you shouldn't use as an opening line",
    "that make people jealous",
    "you would like to add to the Ten Commandments",
    "you love to shop for",
    "you shouldn't try to do in the dark",
    "you would do if you were invisible",
    "you shouldn't do in a group of people",
    "you can't believe someone actually did",
    "that make you angry",
    "you shouldn't have to pay for",
    "you wish had been taught in school",
    "that make you nervous",
    "you wish were delivered",
    "you would like to wake up to",
    "you shouldn't do in a cemetery",
    "that are impossible to measure",
    "you shouldn't do at your wedding",
    "that are better late than never",
    "you never see in the city",
    "that would probably keep you out of heaven",
    "you would like to try",
    "you shouldn't do while golfing",
    "you shouldn't experiment with",
    "that are useless",
    "you shouldn't do on a bus",
    "you would like to do with chocolate",
    "you shouldn't say to break the silence in a conversation",
    "you would do with a million dollars",
    "you wish you could buy out of vending machines",
    "you shoudn't do at a job interview",
    "you shouldn't accept from strangers",
    "you shouldn't do quickly"
  ]

  @doc """
  Gets a random thing
  """
  def random_thing do
    Enum.random(@things)
  end
end
